### ISSUE TITLE
go get时报错,大概是v2ray的一个函数改了

### ISSUE THREAD

**Issue by 2dust** [eycorsican/go-tun2socks-android#1]
cannot use protectedDialer literal (type *protectedDialer) as type internet.SystemDialer in argument to internet.UseAlternativeSystemDialer:
        *protectedDialer does not implement internet.SystemDialer (wrong type for Dial method)
                have Dial(context.Context, "v2ray.com/core/common/net".Address, "v2ray.com/core/common/net".Destination) ("net".Conn, error)
                want Dial(context.Context, "v2ray.com/core/common/net".Address, "v2ray.com/core/common/net".Destination, *internet.SocketConfig) ("net".Conn, error)

**Comment by eycorsican** [comment]
@2dust 刚更新了，用到最新的 v2ray-core

**Comment by 2dust** [comment]
感谢,马上走起
我准备投靠你这边了

**Comment by eycorsican** [comment]
哦。。那你最好先拿这个客户端来各种测一下：https://github.com/eycorsican/kitsunebi-android/releases

老实跟你说，我只是非常简单的测过一下，因为手上的 Android 设备太老太老，卡得没法测什么东西，加上我平时并不用 Android 设备
