### ISSUE TITLE
能否提供aar文件下载

### ISSUE THREAD

**Issue by 2dust** [eycorsican/go-tun2socks-android#2]
暂时没有成功编译出成品,所以有此请求

**Comment by eycorsican** [comment]
成品下载：https://github.com/eycorsican/go-tun2socks-android/releases/tag/v0.1.0

编译步骤没变，估计是你没把依赖更新上去(v2ray-core/go-tun2socks)

**Comment by 2dust** [comment]
谢谢

**Comment by 2dust** [comment]
麻烦你再打包一个最新的aar
我来测试耗电问题,谢谢
